export interface File {
  name: string;
  content: string;
  language: string;
}

export interface Project {
  id: string;
  name: string;
  files: File[];
  messages: Message[]; // Chat history specific to this project
  lastModified: number;
}

export interface GeneratedFile {
  name: string;
  content: string;
  language: string;
}

export interface Message {
  role: 'user' | 'model';
  content: string;
  timestamp: number;
  generatedFiles?: GeneratedFile[]; // Store code generated by AI here
}

export interface Settings {
  enableTailwind: boolean;
  enableBootstrap: boolean;
  firebaseConfig: string;
  selectedModel: string;
}

export interface FileContextType {
  projects: Project[];
  activeProjectId: string | null;
  files: File[];
  messages: Message[]; // Current active project's messages
  selectedFile: File | null;
  createProject: (name: string) => void;
  openProject: (id: string) => void;
  closeProject: () => void;
  deleteProject: (id: string) => void;
  selectFile: (fileName: string) => void;
  updateFileContent: (fileName: string, content: string) => void;
  addFile: (fileName: string, content?: string) => void;
  deleteFile: (fileName: string) => void;
  renameFile: (oldName: string, newName: string) => void;
  addMessage: (message: Message) => void;
  clearMessages: () => void;
}

export interface SettingsContextType {
  settings: Settings;
  updateSettings: (newSettings: Partial<Settings>) => void;
}