
import React, { useState } from 'react';
import { useSettings } from '../context/SettingsContext';
import { X, Save, Shield, Info, MousePointer2, ArrowLeft, Key, ExternalLink, Code2 } from 'lucide-react';

interface Props {
  isOpen: boolean;
  onClose: () => void;
}

const SettingsModal: React.FC<Props> = ({ isOpen, onClose }) => {
  const { settings, updateSettings } = useSettings();
  const [activeView, setActiveView] = useState<'main' | 'privacy' | 'about'>('main');

  if (!isOpen) return null;

  const renderHeader = (title: string) => (
      <div className="flex items-center justify-between p-4 border-b border-ide-border bg-[#1E2028]">
          <div className="flex items-center gap-2">
            {activeView !== 'main' && (
                <button onClick={() => setActiveView('main')} className="text-gray-400 hover:text-white">
                    <ArrowLeft className="w-5 h-5" />
                </button>
            )}
            <h2 className="text-lg font-semibold text-white">{title}</h2>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-white">
            <X className="w-5 h-5" />
          </button>
      </div>
  );

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="bg-ide-panel w-full max-w-md rounded-xl shadow-2xl border border-ide-border animate-in zoom-in-95 duration-200 overflow-hidden">
        
        {activeView === 'main' ? (
             <>
                {renderHeader('App Settings')}
                <div className="p-6 space-y-4 max-h-[70vh] overflow-y-auto custom-scrollbar bg-[#16181D]">
                  
                  {/* Guideline fix: Gemini API Key management UI removed */}

                  <div className="space-y-3">
                      <label className="flex items-center justify-between p-4 bg-white/5 rounded-xl cursor-pointer hover:bg-white/10 transition-colors">
                          <div className="flex items-center gap-3">
                              <MousePointer2 className="w-5 h-5 text-blue-400" />
                              <span className="text-gray-200 text-sm font-bold">PC Cursor Effect</span>
                          </div>
                          <input type="checkbox" checked={settings.enableCustomCursor} onChange={e => updateSettings({enableCustomCursor: e.target.checked})} className="w-5 h-5 rounded border-gray-600 bg-ide-bg text-blue-500" />
                      </label>

                       <button onClick={() => setActiveView('privacy')} className="w-full flex items-center justify-between p-4 bg-white/5 hover:bg-white/10 rounded-xl transition-colors text-left group">
                          <div className="flex items-center gap-3"><Shield className="w-5 h-5 text-green-400" /><span className="text-gray-200 text-sm font-bold">Privacy Policy</span></div>
                          <ArrowLeft className="w-4 h-4 text-gray-500 group-hover:text-white rotate-180" />
                      </button>

                      <button onClick={() => setActiveView('about')} className="w-full flex items-center justify-between p-4 bg-white/5 hover:bg-white/10 rounded-xl transition-colors text-left group">
                          <div className="flex items-center gap-3"><Info className="w-5 h-5 text-purple-400" /><span className="text-gray-200 text-sm font-bold">About App</span></div>
                          <ArrowLeft className="w-4 h-4 text-gray-500 group-hover:text-white rotate-180" />
                      </button>
                  </div>
                </div>
                <div className="p-4 border-t border-ide-border flex justify-end bg-[#1E2028]">
                    <button onClick={onClose} className="px-6 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-sm font-bold shadow-lg shadow-blue-900/20">
                        <Save className="w-4 h-4 inline mr-2" /> Save & Close
                    </button>
                </div>
             </>
        ) : activeView === 'privacy' ? (
            <>
                {renderHeader('Privacy Policy')}
                <div className="p-6 bg-[#16181D] text-gray-300 text-sm space-y-4 max-h-[70vh] overflow-y-auto custom-scrollbar">
                    <h3 className="text-white font-bold">1. Data Ownership</h3>
                    <p>All projects generated by MYSELF IDE are owned by you. We do not claim rights to your code. Data is stored securely on Google Firebase.</p>
                    <h3 className="text-white font-bold">2. Security</h3>
                    <p>We use SSL encryption and industry-standard security practices to protect your workspace. Backend communications use pre-configured environment variables for API security.</p>
                    <h3 className="text-white font-bold">3. Information We Collect</h3>
                    <p>We collect basic profile information (Email, Name) to manage your credits and projects. We do not sell your data to third parties.</p>
                </div>
            </>
        ) : (
             <>
                {renderHeader('About App')}
                <div className="p-8 bg-[#16181D] text-center space-y-4">
                    <div className="w-20 h-20 bg-gradient-to-tr from-blue-600 to-purple-600 rounded-3xl flex items-center justify-center mx-auto mb-4 shadow-xl shadow-blue-500/20">
                        <Code2 className="w-10 h-10 text-white" />
                    </div>
                    <h3 className="text-white font-bold text-2xl">MYSELF IDE</h3>
                    <p className="text-gray-400 text-sm italic">The Ultimate AI-Powered Web Builder</p>
                    <div className="h-px bg-white/5 w-20 mx-auto"></div>
                    <p className="text-gray-400 text-xs leading-relaxed max-w-xs mx-auto">
                        MYSELF IDE is a state-of-the-art browser-based IDE that leverages Google's Gemini AI to help developers and creators build full-stack web applications instantly.
                    </p>
                    <p className="text-gray-500 text-[10px] mt-8">Version 2.6.0 (Stable)<br/>Developed by Wajid Ali</p>
                </div>
            </>
        )}
      </div>
    </div>
  );
};

export default SettingsModal;
